import { Platform, StyleSheet } from "react-native";

const softLift = Platform.select({
  ios: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
  },
  android: { elevation: 8 },
  default: {},
});

const liftStrong = Platform.select({
  ios: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 16,
  },
  android: { elevation: 12 },
  default: {},
});

/** Shared overlay chrome for native map screens (Android OSM + iOS Google). */
export const nativeMapChromeStyles = StyleSheet.create({
  container: { flex: 1 },
  map: { flex: 1 },
  headerContent: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  markerOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2.5,
    backgroundColor: "rgba(255,255,255,0.95)",
    alignItems: "center",
    justifyContent: "center",
  },
  markerInner: { width: 10, height: 10, borderRadius: 5 },
  callout: {
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    minWidth: 180,
    maxWidth: 240,
    gap: 6,
    ...softLift,
  },
  calloutBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, alignSelf: "flex-start" },
  calloutBadgeText: { color: "#fff", fontSize: 9, fontWeight: "800" as const },
  calloutTitle: { fontSize: 14, fontWeight: "700" as const, lineHeight: 19 },
  calloutLocation: { fontSize: 12 },
  calloutTime: { fontSize: 11 },
  summary: {
    position: "absolute",
    left: 16,
    right: 16,
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    ...liftStrong,
  },
  summaryInner: { flexDirection: "row", alignItems: "center", justifyContent: "space-around" },
  statBlock: { alignItems: "center", gap: 4 },
  statNum2: { fontSize: 26, fontWeight: "800" as const },
  statLabel2: { fontSize: 10, fontWeight: "700" as const, letterSpacing: 0.4, opacity: 0.85 },
  divider: { width: 1, height: 36 },
  refreshBtn: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "rgba(37,162,68,0.1)",
  },
  myLocBtn: {
    position: "absolute",
    right: 16,
    borderRadius: 16,
    borderWidth: 1,
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    ...liftStrong,
  },
  routePlannerWrap: {
    position: "absolute",
    left: 14,
    right: 14,
    zIndex: 20,
    borderRadius: 18,
    borderWidth: 1,
    maxHeight: 340,
    overflow: "hidden",
    ...liftStrong,
  },
  routePlannerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  routePlannerTitle: { fontSize: 15, fontWeight: "800" as const },
  routePlannerGo: {
    marginHorizontal: 14,
    marginBottom: 12,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    backgroundColor: "#15803d",
  },
  routePlannerGoText: { color: "#fff", fontWeight: "800" as const, fontSize: 15 },
  routePlannerHint: { fontSize: 12, marginHorizontal: 14, marginBottom: 8, lineHeight: 17 },
});
