import { Platform, StyleSheet } from "react-native";

const softLift = Platform.select({
  ios: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
  },
  android: { elevation: 8 },
  default: {},
});

const liftStrong = Platform.select({
  ios: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 16,
  },
  android: { elevation: 12 },
  default: {},
});

/** Shared overlay chrome for native map screens (Android OSM + iOS Google). */
export const nativeMapChromeStyles = StyleSheet.create({
  container: { flex: 1 },
  map: { flex: 1 },
  headerContent: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  markerOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2.5,
    backgroundColor: "rgba(255,255,255,0.95)",
    alignItems: "center",
    justifyContent: "center",
  },
  markerInner: { width: 10, height: 10, borderRadius: 5 },
  callout: {
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    minWidth: 180,
    maxWidth: 240,
    gap: 6,
    ...softLift,
  },
  calloutBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, alignSelf: "flex-start" },
  calloutBadgeText: { color: "#fff", fontSize: 9, fontWeight: "800" as const },
  calloutTitle: { fontSize: 14, fontWeight: "700" as const, lineHeight: 19 },
  calloutLocation: { fontSize: 12 },
  calloutTime: { fontSize: 11 },
  summary: {
    position: "absolute",
    left: 24,
    right: 24,
    borderRadius: 20,
    borderWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    ...liftStrong,
  },
  /** Three equal slots: Critical | Active | Refresh — avoids uneven space-between gaps. */
  summaryInner: {
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "center",
    width: "100%",
  },
  summaryCell: {
    flex: 1,
    minWidth: 0,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  statBlock: { alignItems: "center", justifyContent: "center", gap: 1 },
  statNum2: { fontSize: 19, fontWeight: "800" as const, letterSpacing: -0.5 },
  statLabel2: { fontSize: 8, fontWeight: "800" as const, letterSpacing: 0.5, opacity: 0.88, textTransform: "uppercase" as const },
  divider: { width: 1, alignSelf: "stretch", minHeight: 30, opacity: 0.55 },
  refreshBtn: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "rgba(37,162,68,0.12)",
  },
  /** Outer frame; inner fill uses LinearGradient in screen. */
  myLocBtn: {
    position: "absolute",
    right: 14,
    borderRadius: 22,
    borderWidth: 0,
    width: 44,
    height: 44,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    ...liftStrong,
  },
  routePlannerWrap: {
    position: "absolute",
    left: 24,
    right: 24,
    zIndex: 20,
    borderRadius: 32,
    borderWidth: 1,
    maxHeight: 520,
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.12,
        shadowRadius: 24,
      },
      android: { elevation: 14 },
      default: {},
    }),
  },
  /** Used inside a modal — no absolute positioning over the map. */
  routePlannerWrapModal: {
    position: "relative",
    left: 0,
    right: 0,
    flex: 0,
    width: "100%",
    maxHeight: 520,
    zIndex: 0,
    alignSelf: "stretch",
  },
  routePlannerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  routePlannerTitle: { fontSize: 18, fontWeight: "800" as const },
  routePlannerGo: {
    marginHorizontal: 20,
    marginBottom: 14,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
    backgroundColor: "#006E26",
  },
  routePlannerGoText: { color: "#fff", fontWeight: "800" as const, fontSize: 15 },
  routePlannerHint: { fontSize: 12, marginHorizontal: 14, marginBottom: 8, lineHeight: 17 },
});
